name: Levantar Node
on: push
jobs:
    checkOut:
        runs-on: ubuntu-20.04

        steps:
            - name: Check-Out del código
              uses: actions/checkout@v2

            - name: Revisar ruta
              run: echo "Ruta del directorio es $GITHUB_WORKSPACE"

            - name: Listar archivos
              run: ls -la $GITHUB_WORKSPACE
            - name: Ejecutar Backend
              run: npm run dev