name: Levantar Node
on: push # pull_request, schedule, workflow_dispatch, repository_dispatch, issues, release
env:
    MI_VAR: "Valor de la variable de action"
jobs:
    checkOut:
        #runs-on: ubuntu-22.04
        runs-on: ${{matrix.os}}
        #Cada job puede tener una matriz
        strategy:
          matrix:
            #os: [ubuntu-22.04, ubuntu-20.04, windows-latest, macos-latest]
            os: [ubuntu-latest, windows-latest, macos-latest]
            node-version: [18.x, 20.x]
        steps:
            - name: Check-Out del código
              uses: actions/checkout@v4

            - run: node --version

            - name: Elegir version node
              uses: actions/setup-node@v4
              with:
                    #node-version: 20
                    node-version: ${{matrix.node-version}}

            - run: node --version

            - name: Revisar ruta
              run: echo "Ruta del directorio es $GITHUB_WORKSPACE"

            - name: Listar archivos
              run: ls -la $GITHUB_WORKSPACE
              #continue-on-error: true

            - name: Correr ante error
              if: ${{failure()}}
              run: echo "Error"
              continue-on-error: true
            
            - name: Instalar dependencias
              run: npm i
              
            #- name: Ejecutar Backend
            #  run: npm run dev

            - name: Mostrar Secret
              run: echo ${{secrets.MI_SECRET}} # No lo muestra por motivos de seguridad

            - name: Mostrar Variable
              run: echo ${{vars.MI_VARIABLE}} # Variable a nivel de repositorio, a nivel de entorno sería env.MIVAR

            - name: Mostrar Variable Action
              run: echo $MI_VAR # Variable a nivel de action
            
              