name: Levantar Node
on: push
jobs:
    checkOut:
        runs-on: ubuntu-20.04

        steps:
            - name: Check-Out del código
              uses: actions/checkout@v2

            - run: node --version

            - name: Elegir version node
              uses: actions/setup-node@v4
              with:
                    node-version: 20

            - run: node --version
            
            - name: Revisar ruta
              run: echo "Ruta del directorio es $GITHUB_WORKSPACE"

            - name: Listar archivos
              run: ls -la $GITHUB_WORKSPACE

            - name: Instalar dependencias
              run: npm i
              
            - name: Ejecutar Backend
              run: npm run dev