name: Decir Hola Mundo
env:
  UBUNTU_VERSION: ubuntu-latest
#on: [push]
on:
  push: 
    branches: [main,dev]
  
  #pull_request:


jobs:
    saludar:
        runs-on: $UBUNTU_VERSION
        steps:
            - name: Decir Hola
              run: echo "Hola Mundo de HaB"
            - name: Pausa
              run: sleep 5
            

    darHora:
      runs-on: $UBUNTU_VERSION
      needs: saludar
      steps:
          - name: Que hora es
            run: echo "La hora del servidor es $(date)"

    despedir:
        runs-on: $UBUNTU_VERSION
        needs: darHora
        steps:            
            - name: Decir Chau
              run: echo "Chau Mundo de HaB"